### PR TITLE
Mailchimp integration

### PR DESCRIPTION
**Pull request by brettnew**
This PR will address [this](https://github.com/JuliaDickey/Red-Sweater-Project-Rails/issues/2) issue with integrating the Mailchimp API to allow the user to enter their email and be added to the Red Sweater newsletter.

Some things to note:
* There seemed to be some existing errors with this functionality; when the user hits the subscribe button, another tab with a hardcoded "Welcome" email message pops up. Would it perhaps be better to do some sort of "welcome" mailer with Mailchimp's API? (I would be willing to work on this)

* This action also creates a subscriber object (well, it would if it could save successfully, which doesn't seem to be happening right now). Was just curious why you would want to save each subscriber to your database when they will be saved on the Mailchimp list?

* The form currently only grabs email. It might be nice for your records to be able to have a first and last name, and this would be pretty easy to implement. I would be willing to do the code for this if you decide that's something you want.

* Finally, I know you talked about wanting this form accessible from the bottom navbar; I could work on this, if you have an example of what you want it to look like for me. (For example, would it be a modal, a tooltip, etc.)

That's it! If you just want to let me know if you want to do any more work on this, I will see what I can do. 😃

### CODE REVIEW

**Comment by JuliaDickey** [comment]
Hey Brett,

    There seemed to be some existing errors with this functionality; when the user hits the subscribe button, another tab with a hardcoded "Welcome" email message pops up. Would it perhaps be tter to do some sort of "welcome" mailer with Mailchimp's API? (I would be willing to work on this)
_If you could automate an email through Mailchimp, that's awesome. It's a gem I installed to send follow up emails with a subscriber model, but we won't need the subscriber model or gem since we're using mailchimp now._ 

    This action also creates a subscriber object (well, it would if it could save successfully, which doesn't seem to be happening right now). Was just curious why you would want to save each subscriber to your database when they will be saved on the Mailchimp list? _The subscriber model isn't needed._ 

    The form currently only grabs email. It might be nice for your records to be able to have a first and last name, and this would be pretty easy to implement. I would be willing to do the code for this if you decide that's something you want. _That's a great idea, if it's not too tricky to implement. Do you think fewer people would sign up if they have to input a name? For initial launch email is ok_

    Finally, I know you talked about wanting this form accessible from the bottom navbar; I could work on this, if you have an example of what you want it to look like for me. (For example, would it be a modal, a tooltip, etc.) _That would be excellent! An input field with a label that says Subscribe. I can design it once it's in. We can talk this out on the phone if it helps. _

**Comment by JuliaDickey** [comment]
If you could make it accessible from the footer, that would be excellent! An input field with a label that says Subscribe. I can design it once it's in. We can talk this out on the phone if it helps.

**Comment by JuliaDickey** [comment]
--Added subscribe forms to footer. 
--Updated API key
Testing tomorrow.

**Comment by JuliaDickey** [comment]
Shifted this to a modal that's triggered from the footer. 

KELSEY: I think we should change the CTA on the homepage to something other than subscribe since it seems a little redundant. What do you think?

**Comment by kelseyfriedman** [comment]
I think we should leave the CTA on the homepage. Not everyone looks at the footer and I think we really want to encourage people to sign up. It's the only place we use that CTA so I think it's okay.... are you okay with that? 

I also want to change the language of the modal to what we have in the CTA because it's not a monthly newsletter "Subscribe to our newsletter and stay up to date with the Mungere School and Red Sweater Project."

I just tested and it worked. My email address is now in the master list in MailChimp. Did you do any test sign ups? I'm not seeing any other new names besides myself. It's possible that it's because you tested with an email that was already on the list.

**Comment by JuliaDickey** [comment]
I tested it about 60 times. :P I deleted the test emails from Mailchimp. I used test@test1.com, test@test2.com...

Copy is updated.

**Comment by kelseyfriedman** [comment]
I'm not familiar with "reviewing" an issue in git. How do I mark it as complete?

**Pull request merged**
